#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo "Usage: create_cpp_project.sh <project_name> [class_name...]"
    exit 1
fi

PROJECT_NAME=$1
shift
mkdir $PROJECT_NAME && cd $PROJECT_NAME

cp ~/.cpp_gen/Makefile .
sed -i "s/NAME =/NAME = $PROJECT_NAME/" Makefile

mkdir includes srcs 

touch srcs/main.cpp
for CLASS_NAME in "$@"
do
    # Create .h file
    echo "#ifndef ${CLASS_NAME}_H" > includes/$CLASS_NAME.h
    echo "# define ${CLASS_NAME}_H" >> includes/$CLASS_NAME.h
    echo "" >> includes/$CLASS_NAME.h
    echo "# include <$CLASS_NAME.hpp>" >> includes/$CLASS_NAME.h
    echo "" >> includes/$CLASS_NAME.h
    echo "#endif" >> includes/$CLASS_NAME.h

    # Create .hpp file
    echo "#ifndef ${CLASS_NAME}_HPP" > includes/$CLASS_NAME.hpp
    echo "# define ${CLASS_NAME}_HPP" >> includes/$CLASS_NAME.hpp
    echo "" >> includes/$CLASS_NAME.hpp
    echo "# include <iostream>" >> includes/$CLASS_NAME.hpp
    echo "" >> includes/$CLASS_NAME.hpp
    echo "typedef std::string t_string;" >> includes/$CLASS_NAME.hpp
    echo "" >> includes/$CLASS_NAME.hpp
    echo "class $CLASS_NAME {" >> includes/$CLASS_NAME.hpp
    echo "	private:" >> includes/$CLASS_NAME.hpp
    echo "" >> includes/$CLASS_NAME.hpp
    echo "	public:" >> includes/$CLASS_NAME.hpp
    echo "		$CLASS_NAME();" >> includes/$CLASS_NAME.hpp
    echo "		~$CLASS_NAME();" >> includes/$CLASS_NAME.hpp
    echo "		$CLASS_NAME(const $CLASS_NAME& other);" >> includes/$CLASS_NAME.hpp
    echo "		$CLASS_NAME& operator=(const $CLASS_NAME& other);" >> includes/$CLASS_NAME.hpp
    echo "};" >> includes/$CLASS_NAME.hpp
    echo "" >> includes/$CLASS_NAME.hpp
    echo "#endif" >> includes/$CLASS_NAME.hpp

    # Create .cpp file
    echo "#include <$CLASS_NAME.h>" > srcs/$CLASS_NAME.cpp
    echo "" >> srcs/$CLASS_NAME.cpp
    echo "$CLASS_NAME::$CLASS_NAME() {}" >> srcs/$CLASS_NAME.cpp
	echo "" >> srcs/$CLASS_NAME.cpp
	echo "$CLASS_NAME::~$CLASS_NAME() {}" >> srcs/$CLASS_NAME.cpp
	echo "" >> srcs/$CLASS_NAME.cpp
	echo "$CLASS_NAME::$CLASS_NAME(const $CLASS_NAME& other) {" >> srcs/$CLASS_NAME.cpp
	echo "	*this = other;" >> srcs/$CLASS_NAME.cpp
	echo "}" >> srcs/$CLASS_NAME.cpp
	echo "" >> srcs/$CLASS_NAME.cpp
	echo "$CLASS_NAME& $CLASS_NAME::operator=(const $CLASS_NAME& other) {" >> srcs/$CLASS_NAME.cpp
	echo "	(void)other;" >> srcs/$CLASS_NAME.cpp
	echo "	return *this;" >> srcs/$CLASS_NAME.cpp
	echo "}" >> srcs/$CLASS_NAME.cpp

	# Add includes to main.cpp

	echo "#include <$CLASS_NAME.h>" >> srcs/main.cpp
done

echo "" >> srcs/main.cpp
echo "int main() {" >> srcs/main.cpp
echo "return 0;" >> srcs/main.cpp
echo "}" >> srcs/main.cpp